server:
  port: ${NOTIFICATION_PORT}

spring:
  config:
    import: "optional:file:../.env[.properties]" # working in >spring boot 2.4

  application:
    name: notification-service

  # db
  datasource:
    # using DB_URL if it's inside container, else use link (local)
    url: ${DB_URL:jdbc:postgresql://127.0.0.1:5433/${DB_NAME_NOTIFICATION}}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  # jpa / hibernate
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

  # RabbitMQ
  rabbitmq: 
    host: ${RABBIT_HOST:localhost}
    port: ${RABBIT_PORT}
    username: ${RABBIT_USER}
    password: ${RABBIT_PASSWORD}

# jwt token
jwt:
  secret: ${JWT_SECRET}
  expiration: ${JWT_EXPIRATION}

#logging
logging:
  level:
    org.hibernate.tool.schema: DEBUG

